id: I64C14AF7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T01:53:57+00:00'
last_modified: '2022-06-08T00:59:16.786883+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21708
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་དཀའ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B31F:
      image_group_id: I4862
      title: ''
      total_pages: 556
      order: 1
      base_file: B31F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
