id: P004433
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21708
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་དཀའ་འགྲེལ
  author: ''
  volumes:
    8e180a9895294b18b85aba565dcf83ce:
      image_group_id: I4862
      title: ''
      volume_number: 1
      total_pages: 556
      base_file: v001.txt
